language: node_js
node_js:
  "7"
install:
  npm install

script:
  - npm run build-production

after_success:
  - docker login -u $DOCKER_ID_USER -p $DOCKER_USER_PASSWORD
  - export TAG=${TRAVIS_TAG:-latest}
  - docker build -t $DOCKER_ID_USER/akseli .
  - docker tag $DOCKER_ID_USER/akseli $DOCKER_ID_USER/akseli:$TAG
  - docker push $DOCKER_ID_USER/akseli