apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: akseli
  labels:
    app: akseli
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: akseli
    spec:
      containers:
        - name: akseli-container
          image: "{{ .Values.akseliImage }}"
          ports:
            - containerPort: 80